pipeline {
    agent any
    stages {
    
        stage('Build the environment'){
            steps {
                sh '''
                ${WORKSPACE}/Script/sh/build.sh
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                ${WORKSPACE}/Script/sh/deploy.sh
                '''
            }
        }
        stage('Sync') {
            steps {
                sh '''
                ${WORKSPACE}/Script/sh/sync.sh
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
     
    }
}