pipeline {
    agent any
    stages {
    
        stage('Build'){
            steps {
                sh '''
                ./Tema9/Script/sh/enviroment.sh
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                ./Tema9/Script/sh/start.sh
                '''
            }
        }
        stage('Sync') {
            steps {
                withAWS(credentials: 'aws-credentials') {
                   sh '''
                    ./Tema9/Script/sh/sync.sh
                ''' 
                }
                
            }
        }
    }
    post {
        always {
            cleanWs()
        }
     
    }
}