version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "single-node" 
    ports:
    - "9200:9200"
    - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.7
    container_name: logstash
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    depends_on:
      - elasticsearch   
    ports:
    - "9600:9600"    
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"  
      xpack.monitoring.enabled: "true"  

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kibana     
    ports:
    - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - elasticsearch