pipeline {
    agent any
    stages {
        stage('Build image'){
            steps{
                sh '''
                chmod +x ./Tema10/Script/sh/image.sh
                ./Tema10/Script/sh/image.sh
                '''
            }
        } 
        stage('Run container'){
            steps {
                sh '''
                chmod +x ./Tema10/Script/sh/container.sh
                ./Tema10/Script/sh/container.sh
                '''
            }
        }
        stage('Sync') {
            steps {
                sh '''
                chmod +x ./Tema10/Script/sh/sync.sh
                ./Tema10/Script/sh/sync.sh
                '''
            }
        }
        stage('Cleanup') {
            steps {
                sh '''
                chmod +x ./Tema10/Script/sh/cleanup.sh
                ./Tema10/Script/sh/cleanup.sh 
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
     
    }
}