pipeline {
    agent any
    stages {
        stage('Build image'){
            steps{
                sh '''
                ls -lha ./Tema10/Script/sh
                ./Tema10/Script/sh/image.sh
                '''
            }
        } 
        stage('Run container'){
            steps {
                sh '''
                ./Tema10/Script/sh/container.sh
                '''
            }
        }
        stage('Sync') {
            steps {
                withAWS(credentials: 'aws-credentials') {
                   sh '''
                    ./Tema10/Script/sh/sync.sh
                ''' 
                } 
            }
        }
        stage('Cleanup') {
            steps {
                sh '''
                ./Tema10/Script/sh/cleanup.sh 
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
     
    }
}
